### ISSUE TITLE
I would be willing to help maintain

### ISSUE THREAD

**Issue by mattyjones** [markcornick/vim-consul#1]
I use many of Hashcorp's tools but my favorites are Vagrant, Consul, and Terraform all of which I would be willing to maintain. When it comes to familiarity with them, I have been using Vagrant for several years and Consul/Consul-Template/Consul-Exec/etc almost daily for about a year. I am starting to really push hard on terraform now which is how I discovered this project.

Many times I am running these on live systems so being able to integrate them with Vim is a huge plus for me as Vim is my editor of choice on both OSX and in my production Linux environment. Over SSH, it is far easier to just execute commands straight from vim rather than drop back in a shell.

I have done some small scale vim scripting in the past but have not had the need to go to crazy with it as most of the time something else already exists and is better than what I could write. I do know vim fairly well from a user perspective and good enough from a developer perspective. I am proficient in several languages including golang, ruby, python, shell, and lua.

For references you can check my [GH](https://github.com/mattyjones) out. I am currently the PM for the [Sensu-Plugins](https://github.com/sensu-plugins) org and have been for over a year now as well as a core member of the dev team and also a contributor to various parts of [Sensu Core](https://github.com/sensu) although I am not an employee or receiving any compensation for this work. I have also contributed to various other monitoring related projects over the years and previously was a doc maintainer for KDE for several years.

**Comment by mcornick** [comment]
Thanks for your interest! I'm about to send an invite to join the Hashivim org. Feel free to work on whatever interests you, as I'm finding I have neither time to work on stuff, nor a list of things to do.

--mark
